feat: edit payment
foxminchan/GovernmentChatbot pull request #53
Opened 2023-11-08 15:19 UTC by NguyenTriBaoThang

## Description

- Create Payment, Guide

## Project

- [ ] Website
- [ ] API
- [ ] Documentation
- [ ] Other... (please describe)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Other... (please describe)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [ ] No tests needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Other... (please describe)

## Screenshots/Videos (if appropriate):

2023-11-08 16:38 UTC, qoucname2202 requested changes
@NguyenTriBaoThang Fix code style for each file has comment

2023-11-08 16:38 UTC, qoucname2202 commented on apps/website/src/features/Payment/index.tsx
> +import bg from '../../assets/images/banners/bg.svg';
@NguyenTriBaoThang Format link image

2023-11-08 16:38 UTC, qoucname2202 commented on apps/website/src/features/Payment/index.tsx
> +      <Typography variant="body1" sx={{
@NguyenTriBaoThang Using className properties tailwindcss

2023-11-08 18:42 UTC, foxminchan requested changes

2023-11-08 18:42 UTC, foxminchan commented on apps/website/src/features/Payment/index.tsx
> +        <img src={imgSrc} alt="icon" style={{ color: '#67A99F' }} />
@NguyenTriBaoThang Image must be have loading lazy

**Docs:** [here](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading)

2023-11-08 19:00 UTC, foxminchan requested changes

2023-11-08 19:00 UTC, foxminchan commented on apps/website/src/features/Payment/index.tsx
> +const CustomLink: React.FC<CustomLinkProps> = ({ to, text, imgSrc }) => {
@NguyenTriBaoThang use tsrfc

2023-11-08 19:00 UTC, foxminchan commented on apps/website/src/features/Policy/index.tsx
> +const CustomListItem: React.FC<CustomListItemProps> = ({ text }) => {
@NguyenTriBaoThang use tsrfc

2023-11-11 11:06 UTC, qoucname2202 approved these changes
@foxminchan Approve merger

2023-11-11 11:44 UTC, foxminchan requested changes
@NguyenTriBaoThang resolve coflict, fix code smell in sonarcloud and file has comment

2023-11-11 11:44 UTC, foxminchan commented on apps/website/src/features/Policy/policy.data.ts
> +export const Section_1 = [
@NguyenTriBaoThang Meaningless variable names

2023-11-11 11:44 UTC, foxminchan commented on apps/website/src/features/Policy/policy.data.ts
> +export const Section_2 = [
@NguyenTriBaoThang Meaningless variable names

2023-11-11 11:44 UTC, foxminchan commented on apps/website/src/features/Policy/policy.data.ts
> +export const Section_4 = [
@NguyenTriBaoThang Meaningless variable names

2023-11-11 11:44 UTC, foxminchan commented on apps/website/src/features/Policy/index.tsx
@NguyenTriBaoThang make sure you have install prettier for format code

**Tools:** [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

2023-11-11 14:56 UTC, foxminchan approved these changes

2023-11-11 14:56 UTC, merged